title: Aaron Meza
description: >-  
  Portfolio, blog, and career hub of Aaron Meza.
baseurl: "" # Leave blank for root
url: "https://www.aaron-meza.com/" # update if using GitHub Pages
theme: minima
markdown: kramdown
